### ISSUE TITLE
French quotes style

### ISSUE THREAD

**Issue by migmake** [carlcs/craft-redactorinlinestyles#1]
Great plugin ! It solved all my client request for redactor improvements.

For info I updated the BO quotes style for french quotes, dont know if it should/could be integrated in the plugin, voilà what I did here, french quotes and space between text and quotes.

.redactor-editor q {
    quotes: '«' '»​' '“' '”' '‘' '’';
}

.redactor-editor q:before {
    content: open-quote;
    margin-right: 5px;
}

.redactor-editor q:after {
    content: close-quote;
    margin-left: 5px;
}

**Comment by carlcs** [comment]
I'm not sure how to best implement customization options, a plain text field in plugin settings?

**Comment by migmake** [comment]
Yes agree I presume plugin settings is the place to put the custom quote sign and space.

**Comment by carlcs** [comment]
This is now possible with the new "cssFile" config setting available to the 2.0 release. Have a look at the cp.css file included in the examples/ folder, I added the CSS necessary to do with french style quotes.

**Comment by migmake** [comment]
Great ! Thanks.
