### ISSUE TITLE
buttonsAdd not adding buttons

### ISSUE THREAD

**Issue by extensibleseth** [carlcs/craft-redactorinlinestyles#11]
I'm hoping this is a case of user error. 

I stepped through the manual installation of cloning the repo and renaming the directory. Then I added "inlinestyles" to the plugins array, and example-1's buttonsAddAfter, and buttonsAdd, bits in Standard.json. I checked that the rich text field was using the Standard config, resaved it for good measure, and edited an entry. No additional buttons or dropdowns were displayed. No new buttons were rendered on the toolbar.

I added some formattingAdd stuff just to make sure I had the right file, and those changes did take effect. The js console didn't show anything untoward, so I'm hoping I've just installed the plugin wrong.

**Comment by carlcs** [comment]
Solved via Slack.
