### ISSUE TITLE
Any items with a class not working

### ISSUE THREAD

**Issue by mmc501** [carlcs/craft-redactorinlinestyles#12]
I have installed the plugin and the example configs - but any of the styles which need a class or span don't seem to work- e.g. the nobr option or any of the colours. When I preview the html - the class doesn't get added.

**Comment by carlcs** [comment]
Yeah, it seems like more recent versions of Redactor have an issue with setting attributes on `<span>` tags. Unfortunatelly we can’t really do anything if the Redactor API is broken.

**Comment by maxstrebel** [comment]
@mmc501 this should be solved if you uncheck the "clean up html" setting.

**Comment by modelesque** [comment]
This only works if I uncheck both "Clean up HTML" and "Purify HTML".  Anyway to get this to work while keeping "Purify HTML" checked?

**Comment by carlcs** [comment]
@rswhite7 you can leave both settings enabled in the latest Craft 3 version of the Redactor plugin.
