### ISSUE TITLE
abbr tag - possible?

### ISSUE THREAD

**Issue by CreateSean** [carlcs/craft-redactorinlinestyles#15]
Is it possible to use this plugin to add a button for the Abbreviation tag?

In the text editor I have CMS, select that text click the abbr button and get an option to add a title which on the front end outputs the html like this?

`<abbr title="Content Management System">CMS</abbr>`

**Comment by carlcs** [comment]
Sorry, but `<abbr>` tags are not possible. It’d require some kind of UI to enter the title attribute similar to the native link button implementation. Thich is quite different to how the rest of the plugin currently works (all styles configurable via the JSON config).
