### ISSUE TITLE
Craft 3 plans?

### ISSUE THREAD

**Issue by proimage** [carlcs/craft-redactorinlinestyles#16]
Are there plans to port this over to Craft 3? Thanks!

**Comment by carlcs** [comment]
Yes, it will be in the store in a week or so.

**Comment by proimage** [comment]
Awesome! Are you going to expand it to cover the other WYSIWYG (CKEditor) as well?

**Comment by carlcs** [comment]
CKEditor is still in alpha and the Craft plugin currently has no way to customize the fields. We will have to wait a bit to see what it will bring.

**Comment by proimage** [comment]
Gotcha, thanks. :)

**Comment by carlcs** [comment]
Decided to wait for P&T to update the Redactor plugin to the new Redactor 3. https://github.com/craftcms/redactor/issues/8

**Comment by ewhicher** [comment]
Great plugin man, any news on this now Redactor 3 is out in the wild?
Thanks!

**Comment by carlcs** [comment]
@ewhicher it is ready yes, but we’ll have to wait for the P&T release.

**Comment by codyjames** [comment]
@carlcs It's out! https://github.com/craftcms/redactor/issues/8

**Comment by jsunsawyer** [comment]
I just updated redactor on one of our sites and found that you can really quickly add your own custom plugin and css.

1. Place a `plugin_name.js` and `plugin_name.css` file in a `config/redactor/plugins` folder. (js file is required but doesn't need to be used)
2. Add `"plugin_name"` to your `"plugins"` setting in any relevant redactor json files.
3. Add your styles to the css file using `.redactor-styles [your selector]`.

I'm not 100% sure you're supposed to be doing this, but it works and doesn't require a plugin!

**Comment by proimage** [comment]
> Place a `plugin_name.js` and `plugin_name.css` file in a config/redactor/plugins folder.
> Add `"plugin_name"` to your `"plugins"` setting...

> ...doesn't require a plugin!

O.o

But seriously, thanks for the tip! ;)

**Comment by carlcs** [comment]
Craft 3 version is out, and the docs will be updated shortly. (Sorry for the delay, I was on holidays when Redactor plugin 2.0 got released).

**Comment by BryceBubbles** [comment]
@carlcs Some docs would be great. The example files help, but some docs would help more :)
