### ISSUE TITLE
Redactor is not defined

### ISSUE THREAD

**Issue by davorpeic** [carlcs/craft-redactorinlinestyles#17]
Hi,

I added some alignment settings from your example, and when I open entry that use redactor I see js error and no customstyles button. Craft CMS 3.0.3.1

![redactor](https://user-images.githubusercontent.com/694091/40275128-7292d61a-5bab-11e8-9133-05da8cc60bb6.jpg)

Any idea what is missing?

thanks

```
{
  "buttons": ["formatting", "bold", "italic", "unorderedlist", "orderedlist", "link", "file", "image", "video"],
  "plugins": ["source", "customstyles", "fullscreen", "video", "clips"],
  "toolbarFixed": true,
  "customStyles": {
    "align": {
      "dropdown": {
        "alignLeft": {
          "api": "module.block.format",
          "args": "p"
        },
        "alignRight": {
          "api": "module.block.format",
          "args": {
            "tag": "p",
            "class": "align-right"
          }
        },
        "alignCenter": {
          "api": "module.block.format",
          "args": {
            "tag": "p",
            "class": "align-center"
          }
        },
        "alignJustify": {
          "api": "module.block.format",
          "args": {
            "tag": "p",
            "class": "align-justify"
          }
        }
      }
    }
  }
}
```

**Comment by carlcs** [comment]
The Redactor plugin 2.0 is installed?

**Comment by davorpeic** [comment]
Not sure if I need to install anything besides the Redactor field I'm using already?

**Comment by carlcs** [comment]
In Settings > Plugins, which version of the Redactor plugin do you have installed?

**Comment by davorpeic** [comment]
Hi, it is Redactor 1.1.0, will update it to 2, I installed the one that comes in plugins store, but I see it is also 2, strange that 1 is installed in the first place
