### ISSUE TITLE
Text disappears when saving Redactor content

### ISSUE THREAD

**Issue by baileydoestech** [carlcs/craft-redactorinlinestyles#18]
Hi there, I'm unsure if this incorrect configuration on my part or a bug with custom styles. The JSON file being used for redactor is shown below:

![image](https://user-images.githubusercontent.com/3185073/41107099-7df45c50-6a69-11e8-8093-81eaf1a25122.png)

This works well when editing and using live preview but when saving the text is no longer visible in the editor.

![image](https://user-images.githubusercontent.com/3185073/41107112-84eb095a-6a69-11e8-9108-6ec1da7ce592.png)

**Comment by carlcs** [comment]
Thanks! Just release 3.0.2 with a fix.

**Comment by carlcs** [comment]
Thanks! Just released 3.0.2 with a fix.
