### ISSUE TITLE
Redactor Remove all styles button

### ISSUE THREAD

**Issue by migmake** [carlcs/craft-redactorinlinestyles#2]
I think you should just add a Remove/Clean All Styles button. It is the only button I miss.
Like here in Redactor Styles plugin.

```
dropdown['remove-styles'] = {
            title: 'Supprimer les styles', func: function () {
                that.styles.resetCustomFormat();
            }
        };
```

**Comment by carlcs** [comment]
Good idea!

**Comment by migmake** [comment]
Thanks for this great plugin carl ! I just wish I had discover it earlier, it would have spare me some days of struggling around these client requests :-)

**Comment by carlcs** [comment]
Added a remove all styles button to the 2.0 release.
