### ISSUE TITLE
Clear Styles not removing Quote

### ISSUE THREAD

**Issue by Djive** [carlcs/craft-redactorinlinestyles#20]
How can I get Clear Styles button to remove Quotes aswell?
Thanks!

**Comment by carlcs** [comment]
It’s a bug in the Redactor API. All this plugin does is to make it possible to configure buttons and dropdown menus and map them to provided API https://imperavi.com/redactor/docs/api-modules/inline/

So all we can do is to report it to Imperavi and hope for a fix.

**Comment by Djive** [comment]
Thanks for a fast reply. 
Will report it to them and keep fingers crossed.
Cheers

**Comment by carlcs** [comment]
Great, let us know what they respond
