### ISSUE TITLE
Readme needs a Usage section

### ISSUE THREAD

**Issue by proimage** [carlcs/craft-redactorinlinestyles#21]
I figured out how to use the plugin by looking in the examples folder, but it took some poking around. The readme could benefit from a "Usage" section to point people in the right direction, even if only to say to look at the `/_examples/redactor/Example.json`. ;)

**Comment by carlcs** [comment]
Yeah I know… 🙁! Added a quick start section for now, docs for configuration will have to wait a bit longer. Sorry
