### ISSUE TITLE
API support

### ISSUE THREAD

**Issue by Visiluna** [carlcs/craft-redactorinlinestyles#24]
Does this plugin support other Redactor APIs than those used in the Example config?

In the example file, an alignment dropdown is defined to align a paragraph left, right, center, or justified. "Align Right," "Align Center," and "Align Justified" work fine by setting the paragraph class to `align-right`, `align-center`, or `align-justify` respectively.

However, selecting "Align Left" _after previously selecting one of the other alignment options_ does nothing.

I was able to "fake it" by modifying the example dropdown object to set an `align-left` class, which is undefined in CSS. Best practices would tell me that it is preferable to remove whichever of the `align-right`, `align-center`, or `align-justify` classes has been previously applied. I just can't get any Redactor API to achieve this. The `module.block.format` used in the example doesn't do it, nor does the `module.block.remove` API.

Is this expected behavior or am I missing something?

Any help is appreciated. TIA.

**Comment by carlcs** [comment]
I am also having the same issue with recent versions of Redactor. The configuration from the Example.json used to work exactly like you want it, the “Align Left” button removed the classes from the paragraph.

Unfortunatelly I don’t see anything in the Redactor changelog that indicates a change, and [according to the docs](https://imperavi.com/redactor/docs/api-modules/#s-format) the default config `"type": "set"` should indeed remove all classes.
 
> `set` (by default) - remove all existing values (classes, attributes or style) and set specified values

I also tried the core `formattingAdd` setting without any luck, which more or less works the same as `customStyles`. https://imperavi.com/redactor/docs/settings/formatting/#s-formattingadd

**Comment by carlcs** [comment]
@Visiluna closing here as Redactor fixed the issue in the meantime.
