### ISSUE TITLE
Change Admin CSS

### ISSUE THREAD

**Issue by nikosdrog** [carlcs/craft-redactorinlinestyles#25]
Hello guys.
I follow the instructions but unfortunately something on redactor have changed.
I need to style my custom classes inside editor but the CSS doesn't work _examples/redactor/resources/example.css.

I use craft 3.4.23.

Thanks

**Comment by carlcs** [comment]
Is the CSS file loaded at all? It needs to be uploaded to config/redactor/resources/.

**Comment by nikosdrog** [comment]
Hi Carlcs. Yes the CSS file is up to the config/redactor/resources/ path.

**Comment by carlcs** [comment]
And you can confirm it’s being loaded (network tab in your browser dev tools)?

**Comment by nikosdrog** [comment]
I checked again with dev tool but it's not load the CSS file. I ll check it again and if i have any problem i ll sent you back. Thanks

**Comment by carlcs** [comment]
I’ll close here as I didn’t hear back.
