### ISSUE TITLE
Custom style adds paragraph above

### ISSUE THREAD

**Issue by havardlj** [carlcs/craft-redactorinlinestyles#26]
I have a added a custom style to add a containing div to selected anchors in my wysiwyg (to be able to turn them into buttons). When I do this, it adds a paragraph with an empty version of the link above that I can't get rid of.

`"button": {
      "title": "Button for link",
      "args": {
        "tag": "div",
        "class": "c-button-wysiwyg"
      }
    },`

`<p><a href="#"></a></p><div class="c-button-wysiwyg"><a href="#">#</a></div>`

**Comment by carlcs** [comment]
Can you try with adding a span? I can imagine Redactor doesn’t want to add a block type element into anchor tags (inline element).

**Comment by carlcs** [comment]
Hm… can you try adding a span? I can imagine Redactor doesn’t want to add a block type element into anchor tags (inline element).
