### ISSUE TITLE
:root:root CSS selector

### ISSUE THREAD

**Issue by craftedsystems** [carlcs/craft-redactorinlinestyles#27]
Hi Christian, 

You set the `:root` CSS selector twice. I guess by mistake.

https://github.com/carlcs/craft-redactorcustomstyles/blob/6d430945e848d530dde6b7387b83eef76b02a7f2/_examples/src/example.scss#L1

Thx

**Comment by carlcs** [comment]
No, it’s actually intended. Chaining the same selector multiple times increases specificity. I learned this trick from a blog post by Harry Roberts. https://csswizardry.com/2014/07/hacks-for-dealing-with-specificity/

Thanks for the heads up!
