### ISSUE TITLE
Required Craft 4 beta

### ISSUE THREAD

**Issue by ghost** [carlcs/craft-redactorinlinestyles#30]
The plugin requires Craft 4 which is still in beta. Can it require craft 3 ?

**Comment by carlcs** [comment]
How are you trying to install, because version 3 requires Craft 3? https://packagist.org/packages/carlcs/craft-redactorcustomstyles#3.0.4

**Comment by ghost** [comment]
It is a fresh install of craft cms 3.7.39 and i used composer
If you check the composer file it is requiring craft cms ^ beta 4

"require": {
    "craftcms/cms": "^4.0.0-beta.1",
    "craftcms/redactor": "^3.0.0-beta.1"
  }

**Comment by carlcs** [comment]
You need to install version 3.

```
composer require carlcs/craft-redactorcustomstyles:^3.0
```
