### ISSUE TITLE
Craft CMS 4.0.5.1  -  Redactor Custom Styles 4.0.1 - Redactor 3.0.0

### ISSUE THREAD

**Issue by nevsie** [carlcs/craft-redactorinlinestyles#32]
Using the default Example.json editor config...

Tear drop - none of these appear to be working. For example highlighting text and selecting "deleted" the text does not become struck through, and the HTML is unchanged

Yet.....
Colour - This does work on highlighted text.

Yet...
Quote, and marked buttons do not work...

Yet...
Favourite button does work!!!
And clear styles does work.

Thoughts?

**Comment by nevsie** [comment]
So, seems anything without the tag defined is a problem.
And no way to apply a class to "current" tag - be it H1 or P or etc

**Comment by carlcs** [comment]
Thanks for reporting this issue. I have just released 4.0.2 with a fix, it was indeed an issue with setting `args` to a string in the button configs.

> And no way to apply a class to "current" tag - be it H1 or P or etc

Yeah, I don‘t think it’s possible to just change class (or other attributes) without defining a tag also.
