### ISSUE TITLE
Backend Javascript stops working

### ISSUE THREAD

**Issue by teachmeter** [carlcs/craft-redactorinlinestyles#34]
What happened?
Description
Recently we've installed our craft 3 project on an Isolated hosting with very strict firewall rules.
We've tried to step by step debug a lot of issues with cookies, sessions, connections made in the backend but we are still encountering such issues.

In the backend in random places we get an error like

BaseElementIndex.js:2121 Uncaught TypeError: Craft.appendFootHtml is not a function
    at s.constructor._createTriggers (BaseElementIndex.js:2121:13)
    at s.constructor.showActionTriggers (BaseElementIndex.js:811:14)
    at s.constructor.updateActionTriggers (BaseElementIndex.js:946:16)
    at s.constructor._handleSelectionChange (BaseElementIndex.js:1668:12)
    at s.constructor.onSelectionChange (BaseElementIndexView.js:345:21)
    at s.constructor.<anonymous> (Select.js:822:25)

My question is is there any kind of guide that would allow us to properly set everything in the firewall security rules or what can cause the beforementioned JS errors?

This seems to happen when your plugin is activated and some ajax requests are made.

# Test case 1 

1. Login to administration as admin 
2. Navigate to assets
3. Check any chekbox in list
4. The js menu for removing/editing assets stops working and console log reports JS errors

# Test Case 2
1. Login
2. Navigate to entries
3. Open an entry
4. User can remove use javascript normally
5. Use module with image attachment
6. Popup appears to select image
7. Images do not have thumbnails, Other data is loaded, The javascript stops working on craft items like save/edit, User is only able to close the popup.

Craft CMS version
Craft Pro 3.7.51

PHP version
8.0.13

Operating system and version
Linux 4.18.0-348.el8.x86_64

Database type and version
MySQL 5.5.5

Image driver and version
GD 8.0.13

Installed plugins and versions
Blitz: 3.12.6
Field Manager: 2.2.5
Imager X: v3.6.2
Navigation: 1.4.28
Redactor: 2.10.10
Redactor Custom Styles: 3.0.4
Retcon: 2.4.3
SEO: dev-develop
Super Table: 2.7.2
Tags: 1.0.9
Typed link field: 1.0.25

**Comment by carlcs** [comment]
Hey there. Are you sure the issue is related to the plugin? To me this sounds like something else is wrong with your installation when core Craft functions can’t be found.

**Comment by teachmeter** [comment]
Hi to be honest I'm not sure exactly but disabling the redactor custom styles plugin seems to fix most of the problems. I can further somehow debug it but maybe you have an idea where could that be.

**Comment by teachmeter** [comment]
@carlcs I talked with my fellow devs and they think we might have some error in a js plugin in the redactor custom styles. Do you have maybe some documentation or a boilerplate for a js plugin? At this point I think it's on us rather than on the plugin. If so i will close the ticket later.
