### ISSUE TITLE
Static translations

### ISSUE THREAD

**Issue by anvart** [carlcs/craft-redactorinlinestyles#38]
I made my json config, everything is working as expected:

```JSON
"customstyles": {
    "Markierungen löschen": {
      "api": "module.inline.clearformat"
    },

    "Link": {
      "api" : "module.inline.format",
      "args": {
        "tag": "span",
        "class": "link",
        "type": "toggle"
      }
    },
    ...
  }
```

And now I need to translate the button names to French. Is there any way to do so?

**Comment by carlcs** [comment]
Translations are registered under “redactor-custom-styles” category, so to add translations in French you’d do that in /fr/redactor-custom-styles.php.
