### ISSUE TITLE
Span support

### ISSUE THREAD

**Issue by lazlo-bonin** [carlcs/craft-redactorinlinestyles#4]
I'm aware the lack of `span` support is known, but I figured starting an issue could help in tracking the bug and having a follow-up. @carlcs, do you have any idea what's causing the bug? Do you have access to the part of the source that's problematic?

**Comment by carlcs** [comment]
There's nothing the plugin can do about it, as it's a problem with Redactor itself.

https://github.com/pixelandtonic/Craft-Release/blob/36010cd04207eae1c5cb4c8be133cf85454b4f84/app/resources/lib/redactor/redactor.js#L4636
