### ISSUE TITLE
Prevent Line Breaks

### ISSUE THREAD

**Issue by jameslindeman** [carlcs/craft-redactorinlinestyles#5]
‘Prevent Line Breaks’ does not seem to work for me (Craft version 2.6.2780). Any known issues? It doesn’t add anything to the HTML in CP or front-end. I’ve tried using the example config.

**Comment by carlcs** [comment]
Thanks James, the example files weren't updated to use `<nobr>` tags instead of `<span>` tags yet. Just pushed a fix https://github.com/carlcs/craft-redactorinlinestyles/archive/9747bf5.zip
