### ISSUE TITLE
Add argument to not override a style of the same element

### ISSUE THREAD

**Issue by carlcs** [carlcs/craft-redactorinlinestyles#6]
It's probably necessary to compare the classes to make it possible to remove a style again.

``` json
{
  "title": "Green",
  "args": ["em", "class", "BasicText—green", "toggle"]
},
{
  "title": "Condensed (All Caps)",
  "args": ["em", "class", "BasicText--condensed", "toggle"]
},
```

**Comment by evanwarner** [comment]
Here's the corresponding documentation in Redactor: https://imperavi.com/redactor/docs/settings/formatting/#setting-formattingAdd

**Comment by carlcs** [comment]
Version 2.0.5 now passes the `args` straight to the `inline.format` function (→ see [API documentation](https://imperavi.com/redactor/docs/api/inline/#api-format)), the plugin used a workaround to apply attributes in the past, as `inline.format` didn’t work reliably to do so.

Unfortunatelly, passing in "toggle" (or "add", "remove") as the forth param didn’t do what I expected. But I’m gonna close this issue, as it’s up to Redactor to fix this and we can’t really do anything about it.
