### ISSUE TITLE
Inline styles are created correctly but once Craft entry is saved they disappear.

### ISSUE THREAD

**Issue by patrickaltair** [carlcs/craft-redactorinlinestyles#9]
I've created a button called smallcaps to assign small caps as an inline style. 

`"buttonsAdd": {
        "smallcaps": {
          "title": "smallcaps",
          "args": ["span","class","smallcaps"]
        }
    }` 

This works well when I edit an entry in craft. It creates a span with the calss "smallcaps" around the text but once I save the entry it doesn't appear. When I open the entry again the span has disappeared. Is this a bug?

**Comment by carlcs** [comment]
Do you have the "Clean up HTML?" setting in the field settings enabled?

**Comment by patrickaltair** [comment]
Ah that was it carcls! I turned it off and it works as intended now. Thank you
